config/routes.rb
Paginas::Engine.routes.draw do
  resources :categories
  resources :pages
  get 'featured', to: 'pages#featured'
  get 'display/:id', to: 'pages#display', as: "display"
  root "pages#index"
end

app/models/paginas/category.rb
module Paginas
  class Category < ActiveRecord::Base
    has_many :pages, :dependent => :destroy
  end
end

app/models/paginas/page.rb
module Paginas
  class Page < ActiveRecord::Base
    belongs_to :category
    validates :title, presence: true
  end
end

app/controllers/paginas/application_controller.rb
  class Paginas::ApplicationController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound do |exception|
         redirect_to root_url, :alert => exception.message
    end
  end

app/controllers/paginas/categories_controller.rb
require_dependency "paginas/application_controller"
module Paginas
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    def index
      @categories = Category.all
    end
    def show
    end
    def new
      @category = Category.new
    end
    def edit
    end
    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to @category, notice: 'Category was successfully created.'
      else
        render :new
      end
    end
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Category was successfully updated.'
      else
        render :edit
      end
    end
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end

    private
      def set_category
        @category = Category.find(params[:id])
      end
      def category_params
        params.require(:category).permit(:name, :description)
      end
  end
end

app/controllers/paginas/pages_controller.rb
require_dependency "paginas/application_controller"
module Paginas
  class PagesController < ApplicationController
    before_action :set_page, only: [:display,:show, :edit, :update, :destroy]
    before_action :set_categories, only: [:edit,:new,:update,:destroy]
    def index
      @pages = Page.all
    end
    def featured
      @pages = Page.where(featured: true)
      render :featured
    end
    def show
    end
    def display
    end
    def new
      @page = Page.new
    end
    def edit
    end
    def create
      @page = Page.new(page_params)
      if @page.save
        redirect_to @page, notice: 'Page was successfully created.'
      else
        render :new
      end
    end
    def update
      if @page.update(page_params)
        redirect_to @page, notice: 'Page was successfully updated.'
      else
        render :edit
      end
    end
    def destroy
      @page.destroy
      redirect_to pages_url, notice: 'Page was successfully destroyed.'
    end

    private
    def set_categories
      @categories = Category.all
    end
    def set_page
      @page = Page.find(params[:id])
    end
    def page_params
      params.require(:page).permit(:title, :text, :featured,:show_title,:category_id)
    end
  end
end

app/helpers/paginas/application_helper.rb
module Paginas
  module ApplicationHelper
    def paginas_menu_helper_by_pages(ids,options = {})
      options[:item_style] ||= "[link]"
      options[:item_separator] ||= " | "
      options[:group_style] ||= "[items]"
      options[:active_class] ||= ""
      options[:controller] ||= 'paginas/pages'
      options[:action] ||= 'display'

      output = ''
      separator = ''
      ids.each do |key,id|
        item = ''
        item += separator
        item += options[:item_style].gsub(/\[link\]/, link_to(key ,display_path(id)))

        active = ''
        if params[:controller] == options[:controller] && params[:action] == options[:action] && params[:id] == id.to_s
          active = options[:active_class]
        end
        item = item.gsub(/\[active\]/, active)
        output += item

        if separator == ''
          separator= options[:item_separator]
        end
    end
      output = options[:group_style].gsub(/\[items\]/, output)

      return output.html_safe
    end
    def paginas_menu_helper_by_cat(catid,options = {})
      options[:item_style] ||= "[link]"
      options[:item_separator] ||= " | "
      options[:group_style] ||= "[items]"
      options[:active_class] ||= ""
      options[:controller] ||= 'paginas/pages'
      options[:action] ||= 'display'

      output = ''
      separator = ''
      cats = Category.where(:id => catid).first
      if !cats.blank?
        cats.pages.each do |page|
          item = ''
          item += separator
          item += options[:item_style].gsub(/\[link\]/, link_to(page.title ,display_path(page.id)))

          active = ''
          if params[:controller] == options[:controller] && params[:action] == options[:action] && params[:id] == page.id.to_s
            active = options[:active_class]
          end
          item = item.gsub(/\[active\]/, active)
          output += item
          if separator == ''
            separator= options[:item_separator]
          end
        end
      end
      output = options[:group_style].gsub(/\[items\]/, output)

      return output.html_safe
    end

    def method_missing(method, *args, &block)
      if (method.to_s.end_with?('_path') || method.to_s.end_with?('_url')) && main_app.respond_to?(method)
        main_app.send(method, *args)
      else
        super
      end
    end
  end
end

app/helpers/paginas/categories_helper.rb
module Paginas
  module CategoriesHelper
  end
end

app/helpers/paginas/pages_helper.rb
module Paginas
  module PagesHelper
  end
end

app/views/paginas/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paginas/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/paginas/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/paginas/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/paginas/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @category.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/paginas/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :show_title %><br>
    <%= f.check_box :show_title %>
  </div>
  <div class="field">
    <%= f.label :featured %><br>
    <%= f.check_box :featured %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id,options_from_collection_for_select(@categories,:id,:name,f.object.category_id)  %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text, :class => "tinymce", :rows => 20, :cols => 80 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paginas/pages/display.html.erb
<%=(@page.show_title)? "<h3>#{@page.title}</h3>".html_safe : "" %> 
<div><%= @page.text.html_safe %></div>

app/views/paginas/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/paginas/pages/featured.html.erb
<% @pages.each do |page| %>
  <%=(page.show_title)? "<h3>#{page.title}</h3>".html_safe : "" %> 
    <div><%= page.text.html_safe %></div>
    </tr>
<% end %>

app/views/paginas/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Pages</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Featured</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.featured %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/paginas/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/paginas/pages/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @page.title %> </h3>

<label>Page Link</label>
<%= text_field_tag :link, display_url(@page), :readonly => 'readonly' %>
<div><%= @page.text.html_safe %></div>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>